/* $NetBSD$ */

/*-
 * Copyright (c) 2017 Jared D. McNeill <jmcneill@invisible.ca>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _ARM_TEGRA_AHUBREG_H
#define _ARM_TEGRA_AHUBREG_H

/*
 * Audio client interface
 */
#define	ACIF_FIFO_THRESHOLD	__BITS(29,24)
#define	ACIF_AUDIO_CHANNELS	__BITS(23,20)
#define	ACIF_CLIENT_CHANNELS	__BITS(19,16)
#define	ACIF_AUDIO_BITS		__BITS(14,12)
#define	ACIF_CLIENT_BITS	__BITS(10,8)
#define	 ACIF_BITS_BIT4		0
#define	 ACIF_BITS_BIT8		1
#define	 ACIF_BITS_BIT12	2
#define	 ACIF_BITS_BIT16	3
#define	 ACIF_BITS_BIT20	4
#define	 ACIF_BITS_BIT24	5
#define	 ACIF_BITS_BIT28	6
#define	 ACIF_BITS_BIT32	7
#define	ACIF_EXPAND		__BITS(7,6)
#define	 ACIF_EXPAND_ZERO	0
#define	 ACIF_EXPAND_ONE	1
#define	 ACIF_EXPAND_LFSR	2
#define	ACIF_STEREO_CONV	__BITS(5,4)
#define	 ACIF_STEREO_CONV_CH0	0
#define	 ACIF_STEREO_CONV_CH1	1
#define	 ACIF_STEREO_CONF_AVG	2
#define	ACIF_REPLICATE		__BITS(3)
#define	ACIF_DIRECTION		__BIT(2)
#define	ACIF_TRUNCATE		__BIT(1)
#define	ACIF_MONO_CONV		__BIT(0)

/*
 * Audio crossbar registers
 */
#define	AUDIO_APBIF_RXn_REG(n)	\
	((n) <= 3 ? (0x00 + ((n) * 0x4)) : (0x44 + ((n) * 0x4)))
#define	AUDIO_I2S_RX0_REG(n)	(0x10 + ((n) * 0x4))
#define	AUDIO_DAMn_RX0_REG(n)	(0x24 + ((n) * 0x8))
#define	AUDIO_DAMn_RX1_REG(n)	(0x28 + ((n) * 0x8))
#define	AUDIO_SPDIF_RXn_REG(n)	(0x3c + ((n) * 0x4))
#define	AUDIO_AMX0_RXn_REG(n)	(0x5c + ((n) * 0x4))
#define	AUDIO_ADX0_RX0_REG	0x6c
#define	AUDIO_BBC1_RXn_REG(n)	(0x70 + ((n) * 0x4))
#define	AUDIO_AMX1_RXn_REG(n)	(0x78 + ((n) * 0x4))
#define	AUDIO_ADX1_RX0_REG	0x88
#define	AUDIO_AFCn_RX0_REG(n)	(0x8c + ((n) * 0x4))

/*
 * APBIF registers
 */
#define	APBIF_CHANNELn_CTRL_REG(n)	(0x00 + ((n) * 0x20))
#define	 APBIF_CHANNEL_CTRL_TX_ENABLE		__BIT(31)
#define	 APBIF_CHANNEL_CTRL_RX_ENABLE		__BIT(30)
#define	 APBIF_CHANNEL_CTRL_LOOPBACK		__BIT(29)
#define	 APBIF_CHANNEL_CTRL_TX_THRESHOLD	__BITS(23,16)
#define	 APBIF_CHANNEL_CTRL_RX_THRESHOLD	__BITS(15,8)
#define	 APBIF_CHANNEL_CTRL_TX_PACK_EN		__BIT(6)
#define	 APBIF_CHANNEL_CTRL_TX_PACK		__BITS(5,4)
#define	 APBIF_CHANNEL_CTRL_RX_PACK_EN		__BIT(2)
#define	 APBIF_CHANNEL_CTRL_RX_PACK		__BITS(1,0)
#define	  APBIF_CHANNEL_CTRL_PACK_NOP		0
#define	  APBIF_CHANNEL_CTRL_PACK_8_4		2
#define	  APBIF_CHANNEL_CTRL_PACK_16		3
#define	APBIF_CHANNELn_CLEAR_REG(n)	(0x04 + ((n) * 0x20))
#define	 APBIF_CHANNEL_CLEAR_TX_SOFT_RESET	__BIT(31)
#define	 APBIF_CHANNEL_CLEAR_RX_SOFT_RESET	__BIT(30)
#define	APBIF_CHANNELn_STATUS_REG(n)	(0x08 + ((n) * 0x20))
#define	APBIF_CHANNELn_TXFIFO_REG(n)	(0x0c + ((n) * 0x20))
#define	APBIF_CHANNELn_RXFIFO_REG(n)	(0x10 + ((n) * 0x20))
#define	APBIF_AUDIOCIF_TXn_CTRL_REG(n)	(0x14 + ((n) * 0x20))
#define	APBIF_AUDIOCIF_RXn_CTRL_REG(n)	(0x18 + ((n) * 0x20))
#define	APBIF_CONFIG_LINK_CTRL_REG	0x80
#define	APBIF_MISC_CTRL_REG		0x84
#define	APBIF_APBDMA_LIVE_STATUS_REG	0x88
#define	APBIF_I2S_LIVE_STATUS_REG	0x8c
#define	APBIF_DAM0_LIVE_STATUS_REG	0x90
#define	APBIF_DAM1_LIVE_STATUS_REG	0x98
#define	APBIF_DAM2_LIVE_STATUS_REG	0xa0
#define	APBIF_SPDIF_LIVE_STATUS_REG	0xa8
#define	APBIF_I2S_INT_MASK_REG		0xb0
#define	APBIF_DAM_INT_MASK_REG		0xb4
#define	APBIF_SPDIF_INT_MASK_REG	0xbc
#define	APBIF_APBIF_INT_MASK_REG	0xc0
#define	APBIF_I2S_INT_STATUS_REG	0xc8
#define	APBIF_DAM_INT_STATUS_REG	0xcc
#define	APBIF_SPDIF_INT_STATUS_REG	0xd4
#define	APBIF_APBIF_INT_STATUS_REG	0xd8
#define	APBIF_I2S_INT_SOURCE_REG	0xe0
#define	APBIF_DAM_INT_SOURCE_REG	0xe4
#define	APBIF_SPDIF_INT_SOURCE_REG	0xec
#define	APBIF_APBIF_INT_SOURCE_REG	0xf0
#define	APBIF_I2S_INT_SET_REG		0xf8
#define	APBIF_DAM_INT_SET_REG		0xfc
#define	APBIF_SPDIF_INT_SET_REG		0x100
#define	APBIF_APBIF_INT_SET_REG		0x104
#define	APBIF_APBDMA_LIVE_TX_DMA_FIFO_EMPTY_STATUS_REG	0x10c
#define	APBIF_APBDMA_LIVE_TX_CIF_FIFO_EMPTY_STATUS_REG	0x110
#define	APBIF_APBDMA_LIVE_RX_DMA_FIFO_EMPTY_STATUS_REG	0x114
#define	APBIF_APBDMA_LIVE_RX_CIF_FIFO_EMPTY_STATUS_REG	0x118
#define	APBIF_APBDMA_LIVE_TX_DMA_FIFO_FULL_STATUS_REG	0x11c
#define	APBIF_APBDMA_LIVE_TX_CIF_FIFO_FULL_STATUS_REG	0x120
#define	APBIF_APBDMA_LIVE_RX_DMA_FIFO_FULL_STATUS_REG	0x124
#define	APBIF_APBDMA_LIVE_RX_CIF_FIFO_FULL_STATUS_REG	0x128
#define	APBIF_APBIF_RXCIF_UNDERRUN_INT_MASK_REG		0x12c
#define	APBIF_APBIF_TXCIF_OVERRUN_INT_MASK_REG		0x130
#define	APBIF_APBIF_APBDMA_UNDERRUN_INT_MASK_REG	0x134
#define	APBIF_APBIF_APBDMA_OVERRUN_INT_MASK_REG		0x138
#define	APBIF_APBIF_RXCIF_UNDERRUN_INT_STATUS_REG	0x13c
#define	APBIF_APBIF_TXCIF_OVERRUN_INT_STATUS_REG	0x140
#define	APBIF_APBIF_APBDMA_UNDERRUN_INT_STATUS_REG	0x144
#define	APBIF_APBIF_APBDMA_OVERRUN_INT_STATUS_REG	0x148
#define	APBIF_APBIF_RXCIF_UNDERRUN_INT_SOURCE_REG	0x14c
#define	APBIF_APBIF_TXCIF_OVERRUN_INT_SOURCE_REG	0x150
#define	APBIF_APBIF_APBDMA_UNDERRUN_INT_SOURCE_REG	0x154
#define	APBIF_APBIF_APBDMA_OVERRUN_INT_SOURCE_REG	0x158
#define	APBIF_APBIF_RXCIF_UNDERRUN_INT_SET_REG		0x15c
#define	APBIF_APBIF_TXCIF_OVERRUN_INT_SET_REG		0x160
#define	APBIF_APBIF_APBDMA_UNDERRUN_INT_SET_REG		0x164
#define	APBIF_APBIF_APBDMA_OVERRUN_INT_SET_REG		0x168
#define	APBIF_AMX0_LIVE_STATUS_REG			0x178
#define	APBIF_AMX1_LIVE_STATUS_REG			0x17c
#define	APBIF_ADX0_LIVE_STATUS_REG			0x180
#define	APBIF_ADX1_LIVE_STATUS_REG			0x184
#define	APBIF_AMX_INT_MASK_REG				0x188
#define	APBIF_ADX_INT_MASK_REG				0x190
#define	APBIF_AMX_INT_STATUS_REG			0x198
#define	APBIF_ADX_INT_STATUS_REG			0x1a0
#define	APBIF_AMX_INT_SOURCE_REG			0x1a8
#define	APBIF_ADX_INT_SOURCE_REG			0x1b0
#define	APBIF_AMX_INT_SET_REG				0x1b8
#define	APBIF_ADX_INT_SET_REG				0x1c0
#define	APBIF_MISC_LIVE_STATUS0_REG			0x1d0
#define	APBIF_MISC_LIVE_STATUS1_REG			0x1d4
#define	APBIF_MISC_LIVE_STATUS2_REG			0x1d8
#define	APBIF_MISC_LIVE_STATUS3_REG			0x1dc

/*
 * APBIF2 registers
 */
#define	APBIF2_CHANNELn_CTRL_REG(n)	(0x00 + ((n) * 0x20))
#define	APBIF2_CHANNELn_CLEAR_REG(n)	(0x04 + ((n) * 0x20))
#define	APBIF2_CHANNELn_STATUS_REG(n)	(0x08 + ((n) * 0x20))
#define	APBIF2_CHANNELn_TXFIFO_REG(n)	(0x0c + ((n) * 0x20))
#define	APBIF2_CHANNELn_RXFIFO_REG(n)	(0x10 + ((n) * 0x20))
#define	APBIF2_AUDIOCIF_TXn_CTRL_REG(n)	(0x14 + ((n) * 0x20))
#define	APBIF2_AUDIOCIF_RXn_CTRL_REG(n)	(0x18 + ((n) * 0x20))
#define	APBIF2_AFC_LIVE_TX_FIFO_EMPTY_STATUS_REG	0xc0
#define	APBIF2_AFC_LIVE_TX_FIFO_FULL_STATUS_REG		0xc4
#define	APBIF2_AFC_LIVE_RX_FIFO_EMPTY_STATUS_REG	0xc8
#define	APBIF2_AFC_LIVE_RX_FIFO_FULL_STATUS_REG		0xcc
#define	APBIF2_AFC_LIVE_TX_ENABLED_STATUS_REG		0xd0
#define	APBIF2_AFC_TX_DONE_INT_MASK_REG			0xd4
#define	APBIF2_AFC_FLOW_CTL_INT_MASK_REG		0xd8
#define	APBIF2_AFC_TX_DONE_INT_STATUS_REG		0xdc
#define	APBIF2_AFC_FLOW_CTL_INT_STATUS_REG		0xe0
#define	APBIF2_AFC_TX_DONE_INT_SOURCE_REG		0xe4
#define	APBIF2_AFC_FLOW_CTL_INT_SOURCE_REG		0xe8
#define	APBIF2_AFC_TX_DONE_INT_SET_REG			0xec
#define	APBIF2_AFC_FLOW_CTL_INT_SET_REG			0xf0
#define	APFIF2_AFC_MISC_LIVE_STATUS0_REG		0xf4

#endif /* _ARM_TEGRA_AHUBREG_H */
